version: '3.1'

services:

  tatm-bff:
    build: 
      context: ./bff
      dockerfile: ./Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - packages.vaudoise.ch/dockerhub/node:lts-alpine


  tatm-front:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    ports: 
      - 4200:80
    depends_on: 
      - packages.vaudoise.ch/dockerhub/nginx
